# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ShvatkaBotTest

on:
  workflow_call:

  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - &checkout
        uses: actions/checkout@v2
      - &install-poetry
        name: Install poetry
        run: pipx install poetry
      - &setup-python
        name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: "poetry"
          cache-dependency-path: poetry.lock
      - name: Install dependencies
        run: poetry install --with test
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *install-poetry
      - *setup-python

      - name: black
        run: poetry run black --check --verbose .
      - name: flake8
        run: poetry run flake8 .
  type-checker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *install-poetry
      - *setup-python

      - name: mypy
        run: poetry run mypy .
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *install-poetry
      - *setup-python

      - name: Test with pytest
        run: poetry run pytest
